name: Build Debian Base Image

on:
  push:
    paths:
      - 'docker/debian-base.dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push slim base
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/debian-base.dockerfile
          target: base2-slim
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uptime-kuma:base2-slim

      - name: Build and push full base
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/debian-base.dockerfile
          target: base2
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uptime-kuma:base2